apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
     app: webserver
  name: webapplication
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - image: nginx:1.18
          name: webserver
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi
