apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
     app: webserver1
  name: webapplication
spec:
  revisionHistoryLimit: 10
  replicas: 5
  strategy:
#    type: Recreate
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - image: nginx:1.16
          name: webserver
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi