apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver1
    app.kubernetes.io/instance: nginx
  name: webservice
  namespace: default
spec:
  ports:
  - nodePort: 31563
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: webserver
  sessionAffinity: None
  type: NodePort
