apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
#      annotations:
#        configmap.reloader.stakater.com/reload: "nginx-config"
    spec:
      containers:
      - name: web
        image: nginx:1.16
        ports:
          - name: webport
            containerPort: 80
            protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: "/etc/nginx/conf.d/"
          readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginxconfigmap


