apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx
#  nodeSelector:
#    disktype: slow

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    env: test
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx
#  nodeSelector:
#    disktype: slow
