apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web1
  namespace: prakash
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: NodePort