apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
    
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-replica
  name: postgres-replica

spec:
  type: ClusterIP
  ports:
  - name: postgres-replica
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-replica
    
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-lb
spec:
  type: LoadBalancer
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-replica
  name: postgres-replica-lb

spec:
  type: LoadBalancer
  ports:
  - name: postgres-replica
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-replica