apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webapp-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nginx

---
#
#apiVersion: policy/v1
#kind: PodDisruptionBudget
#metadata:
#  name: webapp-pdb
#spec:
#  maxUnavailable: 1
#  selector:
#    matchLabels:
#      app: webserver