apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserver
  name: webserver
  namespace: dev
spec:
  containers:
    - image: nginx:1.20
      name: webserver
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 64Mi
#    - image: nginx:1.20
#      name: webserver1
#      resources:
#        requests:
#          cpu: 200m
#          memory: 64Mi
#        limits:
#          cpu: 200m
#          memory: 64Mi