apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: QARoleBinding
  namespace: qa
subjects:
  - kind: Group
    name: qa
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: qa-role


---

kubectl config set-credentials venkat --client-certificate=venkat.crt  --client-key=venkat.key
kubectl config set-context venkat-context --cluster=minikube --namespace=qa --user=venkat