apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-alertmanager
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/alertmanager"