apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
spec:
  volumes:
  - name: cloud-storage
    persistentVolumeClaim:
      claimName: aws-pvc
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: cloud-storage
      mountPath: /cloud/data