apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv-sc
  labels:
    type: sc
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-storage-class
  persistentVolumeReclaimPolicy: Retain