apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-pvc-sc-new
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: ebs-storage-class-new

