apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
#provisioner: ebs.csi.aws.com
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - us-east-2a
