apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-storage-class-new
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
#provisioner: ebs.csi.aws.com
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
#allowedTopologies:
#  - matchLabelExpressions:
#    - key: topology.ebs.csi.aws.com/zone
#      values:
#      - us-east-1a
