apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-secret
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
#      annotations:
#        configmap.reloader.stakater.com/reload: "nginx-config"
    spec:
      containers:
      - name: web
        image: cateringapplication
        ports:
          - name: webport
            containerPort: 80
            protocol: TCP
        volumeMounts:
        - name: webserver-ssl
          mountPath: "/etc/nginx/ssl"
          readOnly: true
      volumes:
        - name: webserver-ssl
          secret:
            secretName: websecret


